# Generated by Django 3.2.13 on 2022-04-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='courier_id',
        ),
        migrations.AddField(
            model_name='income',
            name='courier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='couriers.user'),
        ),
    ]
