# Generated by Django 3.2.13 on 2022-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_auto_20220421_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(default=0)),
                ('income', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='IncomeReport',
            new_name='IncomeDailyReport',
        ),
    ]
