# Generated by Django 3.2.13 on 2022-04-22 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_auto_20220421_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedailyreport',
            name='courier_id',
        ),
        migrations.RemoveField(
            model_name='incomeweeklyreport',
            name='courier_id',
        ),
        migrations.AddField(
            model_name='incomedailyreport',
            name='courier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='couriers.user'),
        ),
        migrations.AddField(
            model_name='incomeweeklyreport',
            name='courier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='couriers.user'),
        ),
    ]
