# Generated by Django 3.2.13 on 2022-04-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_auto_20220422_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeweeklyreport',
            name='courier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='couriers.user'),
        ),
    ]
