# Generated by Django 3.2.13 on 2022-04-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_alter_incomeweeklyreport_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
